version: "2.4"

services:
  traefik:
    isolation: default
    image: traefik:v2.2.0-windowsservercore-1809
    command:
      - "--providers.docker.endpoint=npipe:////./pipe/docker_engine"
      - "--providers.docker.exposedByDefault=false"
      - "--api.insecure=true"      
      - "--log.level=DEBUG"      
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web-secure.address=:443"      
      - "--providers.file.directory=C:/etc/traefik/config/dynamic"
    ports:
      - "8080:80"
      - "443:443"
      - "8079:8080"
    volumes:
        - source: \\.\pipe\docker_engine
          target: \\.\pipe\docker_engine
          type: npipe      
        - ./.docker/traefik:C:/etc/traefik
    depends_on:
      - solr
      - cm
      - cd
    container_name: globags_sc_traefik  
  sql:
    image: ${REGISTRY}/sitecore-xm-sxa-sqldev:${SITECORE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
    volumes:
      - sql_data:C:\Data
    mem_limit: 2GB
    ports:
      - "44010:1433"
    environment:
      SA_PASSWORD: ${SQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    container_name: globags_sc_sql  
  solr:
    image: ${REGISTRY}/sitecore-xm-sxa-solr:${SITECORE_VERSION}-nanoserver-${NANOSERVER_VERSION}
    volumes:
      - solr_data:C:\Data
    mem_limit: 1GB
    ports:
      - "44011:8983"
    environment:
      SOLR_LOG_LEVEL: INFO
    container_name: globags_sc_solr 
  cd:
    image: ${REGISTRY}/sitecore-xm-sxa-cd:${SITECORE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
    entrypoint: powershell.exe -Command "& C:\\tools\\entrypoints\\iis\\Development.ps1"
    environment:
      SITECORE_LICENSE_LOCATION: C:\license\license.xml
      SITECORE_APPSETTINGS_ROLE:DEFINE: ContentDelivery
      SITECORE_CONNECTIONSTRINGS_SECURITY: Data Source=sql;Initial Catalog=Sitecore.Core;User ID=sa;Password=${SQL_SA_PASSWORD}
      SITECORE_CONNECTIONSTRINGS_WEB: Data Source=sql;Initial Catalog=Sitecore.Web;User ID=sa;Password=${SQL_SA_PASSWORD}
      SITECORE_CONNECTIONSTRINGS_EXPERIENCEFORMS: Data Source=sql;Initial Catalog=Sitecore.ExperienceForms;User ID=sa;Password=${SQL_SA_PASSWORD}
      SITECORE_CONNECTIONSTRINGS_SOLR.SEARCH: http://solr:8983/solr
      ENTRYPOINT_STDOUT_IIS_ACCESS_LOG_ENABLED: 'true'
      ENTRYPOINT_STDOUT_IIS_ERROR_LOG_ENABLED: 'true'
      ENTRYPOINT_STDOUT_SITECORE_LOG_ENABLED: 'true'
    depends_on:
      sql:
        condition: service_healthy
      solr:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.force-STS-Header.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.force-STS-Header.headers.stsSeconds=31536000"
      - "traefik.http.routers.cd-secure.middlewares=force-STS-Header"
      - "traefik.http.routers.cd-secure.entrypoints=web-secure"
      - "traefik.http.routers.cd-secure.rule=Host(`${HOSTNAME_CD}`)"                  
      - "traefik.http.routers.cd-secure.tls=true"
    volumes:
      - .\deploy:C:\src
      - C:\license:C:\license:ro 
      - C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Remote Debugger:C:\remote_debugger
    container_name: globags_sc_cd  
  cm:
    image: ${REGISTRY}/sitecore-xm-sxa-cm:${SITECORE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
    entrypoint: powershell.exe -Command "& C:\\tools\\entrypoints\\iis\\Development.ps1"
    environment:
      SITECORE_LICENSE_LOCATION: C:\license\license.xml
      SITECORE_APPSETTINGS_ROLE:DEFINE: ContentManagement, Indexing
      SITECORE_CONNECTIONSTRINGS_CORE: Data Source=sql;Initial Catalog=Sitecore.Core;User ID=sa;Password=${SQL_SA_PASSWORD}
      SITECORE_CONNECTIONSTRINGS_SECURITY: Data Source=sql;Initial Catalog=Sitecore.Core;User ID=sa;Password=${SQL_SA_PASSWORD}
      SITECORE_CONNECTIONSTRINGS_MASTER: Data Source=sql;Initial Catalog=Sitecore.Master;User ID=sa;Password=${SQL_SA_PASSWORD}
      SITECORE_CONNECTIONSTRINGS_WEB: Data Source=sql;Initial Catalog=Sitecore.Web;User ID=sa;Password=${SQL_SA_PASSWORD}
      SITECORE_CONNECTIONSTRINGS_EXPERIENCEFORMS: Data Source=sql;Initial Catalog=Sitecore.ExperienceForms;User ID=sa;Password=${SQL_SA_PASSWORD}
      SITECORE_CONNECTIONSTRINGS_SOLR.SEARCH: http://solr:8983/solr
      SITECORE_APPSETTINGS_TELERIK.ASYNCUPLOAD.CONFIGURATIONENCRYPTIONKEY: ${TELERIK_ENCRYPTION_KEY}
      SITECORE_APPSETTINGS_TELERIK.UPLOAD.CONFIGURATIONHASHKEY: ${TELERIK_ENCRYPTION_KEY}
      SITECORE_APPSETTINGS_TELERIK.WEB.UI.DIALOGPARAMETERSENCRYPTIONKEY: ${TELERIK_ENCRYPTION_KEY}
      ENTRYPOINT_STDOUT_IIS_ACCESS_LOG_ENABLED: 'false'
      ENTRYPOINT_STDOUT_IIS_ERROR_LOG_ENABLED: 'false'
      ENTRYPOINT_STDOUT_SITECORE_LOG_ENABLED: 'true'
    depends_on:
      sql:
        condition: service_healthy
      solr:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.force-STS-Header.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.force-STS-Header.headers.stsSeconds=31536000"
      - "traefik.http.routers.cm-secure.middlewares=force-STS-Header"
      - "traefik.http.routers.cm-secure.entrypoints=web-secure"
      - "traefik.http.routers.cm-secure.rule=Host(`${HOSTNAME_CM}`)"                  
      - "traefik.http.routers.cm-secure.tls=true"
    volumes:
      - .\deploy:C:\src
      - .\Unicorn:C:\inetpub\wwwroot\App_Data\Unicorn\globags
      - C:\license:C:\license:ro 
      - C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Remote Debugger:C:\remote_debugger
    container_name: globags_sc_cm  
volumes:
    sql_data:
    solr_data: