---
ID: "7872c09d-33fb-499d-852c-29bfa6721416"
Parent: "7b362e49-d803-4876-abf8-ef28e6696920"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/templates/Branches/Feature/Globags Inc/Promos/Default Promo Variant/$name/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160427T134629Z
