---
ID: "14dc5274-7e9b-44c0-9a5a-5a0b9caee397"
Parent: "57b72368-2fe4-4563-95ef-e388f6e0181d"
Template: "8b649372-cc12-4f31-802a-8c3b3d09bb3f"
Path: /sitecore/content/Globags Inc/globags/Settings/Scopes/Product Templates
DB: master
SharedFields:
- ID: "b04fe662-2b23-44dd-b971-2b864a1ec55f"
  Hint: ScopeQuery
  Value: "+template:{333fb57c-5bc0-4be9-aef2-fa0569bb93de}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200801T235107Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
