---
ID: "48e4f7c1-b572-4dab-a45f-317010fa9ad8"
Parent: "feaa0e4e-c5b2-4689-bb82-ef8a472a8af1"
Template: "292ccfcd-7790-4692-856b-76014b8038e7"
Path: /sitecore/system/Settings/Feature/Globags Inc/Products/Products Site Setup
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200730T215240Z
    - ID: "c202067e-7fab-4606-afb4-e76df2185ddc"
      Hint: Name
      Value: Products
