---
ID: "5bef7264-9e46-47e7-9d4d-561491cbca4f"
Parent: "feaa0e4e-c5b2-4689-bb82-ef8a472a8af1"
Template: "141df88e-7156-4d2e-a004-c8c1a7c51e9d"
Path: /sitecore/system/Settings/Feature/Globags Inc/Products/Products Tenant Setup
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200730T215239Z
    - ID: "c202067e-7fab-4606-afb4-e76df2185ddc"
      Hint: Name
      Value: Products
