---
ID: "4aed5cf4-dbfe-4a10-a668-6215d070cebe"
Parent: "333fb57c-5bc0-4be9-aef2-fa0569bb93de"
Template: "333fb57c-5bc0-4be9-aef2-fa0569bb93de"
Path: /sitecore/templates/Project/Globags Inc/Globags/Pages/Product Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200730T222510Z
