---
ID: "8fe4afb3-4541-42f4-ad38-1faec1edc137"
Parent: "16ea3ce6-acb9-4ba4-9d41-01a5d35fc130"
Template: "16ea3ce6-acb9-4ba4-9d41-01a5d35fc130"
Path: /sitecore/templates/Feature/Globags Inc/Carousel/Globags Carousel/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{D613F89C-559C-45A9-9275-8DE125E07313}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20111206T102520Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
