---
ID: "722dd87a-32ab-48d3-968b-6223d3c59666"
Parent: "6b3084c9-fea2-4c09-baeb-d038331cb54a"
Template: "333fb57c-5bc0-4be9-aef2-fa0569bb93de"
Path: /sitecore/content/Globags Inc/globags/Home/Products/Product 2
DB: master
SharedFields:
- ID: "97fb669d-5b8e-4829-9a24-06418c315d73"
  Hint: SxaTags
  Value: "{FEE282E8-E4A6-4FC7-BB32-226AC92309B9}|{ABC562BC-3123-440D-9774-AA1D78877A60}|{CFFBD533-B6AA-4D85-8760-5A37EDD3BD35}"
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200801T000201Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Product 2
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "ba792e7c-7352-419a-8dc9-65674c67e6b6"
      Hint: Title
      Value: Product 2
- Language: "de-LU"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200801T000201Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Product 2
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "ba792e7c-7352-419a-8dc9-65674c67e6b6"
      Hint: Title
      Value: Product 2
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200801T000201Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Product 2
    - ID: "ba792e7c-7352-419a-8dc9-65674c67e6b6"
      Hint: Title
      Value: Product 2
- Language: "fr-FR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200801T000201Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Product 2
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "ba792e7c-7352-419a-8dc9-65674c67e6b6"
      Hint: Title
      Value: Product 2
